const menu=[
{id:1,name:"Vada Pav",price:20,emoji:"🍔",portions:{Small:0.7,Regular:1,Large:1.4}},
{id:2,name:"Samosa",price:15,emoji:"🥟",portions:{Small:0.7,Regular:1,Large:1.4}},
{id:3,name:"Sandwich",price:40,emoji:"🥪",portions:{Small:0.7,Regular:1,Large:1.4}},
{id:4,name:"Tea",price:10,emoji:"☕",portions:{Small:0.7,Regular:1,Large:1.4}},
{id:5,name:"Cold Coffee",price:50,emoji:"🥤",portions:{Small:0.7,Regular:1,Large:1.4}},
{id:6,name:"Veg Noodles",price:60,emoji:"🍜",portions:{Small:0.7,Regular:1,Large:1.4}}
];
let cart=JSON.parse(localStorage.getItem("cgCart")||"[]");
let orders=JSON.parse(localStorage.getItem("cgOrders")||"[]");
function save(){localStorage.setItem("cgCart",JSON.stringify(cart));localStorage.setItem("cgOrders",JSON.stringify(orders))}
function showPage(id,btn){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));btn.classList.add("active");if(id==="canteenPage")renderOrders()}
function renderMenu(){document.getElementById("menuGrid").innerHTML=menu.map(i=>`<div class="menu-card"><div class="food-image">${i.emoji}</div><h3>${i.name}</h3><div class="price">₹${i.price} base price</div><label class="portion-label">Choose portion</label><select class="portion-select" id="portion-${i.id}"><option>Small — 70%</option><option selected>Regular — 100%</option><option>Large — 140%</option></select><input class="note-input" id="note-${i.id}" placeholder="Optional note: less spicy"><button class="primary-btn" onclick="addToCart(${i.id})">Add Selected Portion</button></div>`).join("")}
function addToCart(id){let item=menu.find(x=>x.id===id),select=document.getElementById("portion-"+id),portion=select.value.split(" ")[0],note=document.getElementById("note-"+id).value.trim();let existing=cart.find(x=>x.id===id&&x.portion===portion&&x.note===note);if(existing)existing.qty++;else cart.push({id,name:item.name,emoji:item.emoji,basePrice:item.price,portion,note,qty:1,price:Math.round(item.price*item.portions[portion])});save();renderCart()}
function changeQty(index,delta){cart[index].qty+=delta;if(cart[index].qty<=0)cart.splice(index,1);save();renderCart()}
function clearCart(){cart=[];save();renderCart()}
function renderCart(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0);document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)+" items";document.getElementById("cartTotal").textContent=total;document.getElementById("cartItems").innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div class="cart-row-top"><b>${x.emoji} ${x.name}</b><b>₹${x.price*x.qty}</b></div><div class="cart-row-bottom"><span>${x.portion} portion × ${x.qty}${x.note?` • Note: ${x.note}`:""}</span><span class="qty"><button onclick="changeQty(${i},-1)">−</button><button onclick="changeQty(${i},1)">+</button></span></div></div>`).join(""):"<p>Your cart is empty. Choose a portion to begin.</p>"}
function placeOrder(){if(!cart.length){alert("Please add food items first.");return}let token=orders.length?Math.max(...orders.map(o=>o.token))+1:101;let total=cart.reduce((s,x)=>s+x.price*x.qty,0),items=cart.map(x=>({...x}));let order={id:Date.now(),token,items,total,status:"Pending",time:new Date().toLocaleTimeString(),created:Date.now()};orders.push(order);cart=[];save();renderCart();document.getElementById("studentMessage").textContent=`Order placed! Token #${token}. Your portion choices have been saved.`}
function priority(o){let count=o.items.reduce((s,x)=>s+x.qty,0),small=o.items.filter(x=>x.portion==="Small").length;return small>0||count<=2?"High":"Normal"}
function nextOrder(){return orders.filter(o=>o.status==="Pending").sort((a,b)=>(priority(a)==="High"?0:1)-(priority(b)==="High"?0:1)||a.created-b.created)[0]}
function updateStatus(id,status){let o=orders.find(x=>x.id===id);if(o){o.status=status;save();renderOrders()}}
function renderOrders(){let c={Pending:0,Preparing:0,Ready:0,Collected:0};orders.forEach(o=>c[o.status]++);["Pending","Preparing","Ready","Collected"].forEach((x,i)=>document.getElementById(["pendingCount","preparingCount","readyCount","completedCount"][i]).textContent=c[x]);let n=nextOrder();document.getElementById("priorityRecommendation").textContent=n?`Prepare Token #${n.token} next. ${priority(n)} priority because of portion size/order load.`:"No pending orders yet.";document.getElementById("ordersList").innerHTML=orders.length?orders.slice().reverse().map(o=>`<div class="order-card"><div class="order-info"><h3>Token #${o.token} <span class="status-badge">${o.status}</span></h3><p>${o.items.map(x=>`${x.emoji} ${x.name} — ${x.portion} × ${x.qty}${x.note?` (${x.note})`:""}`).join(", ")}</p><p>Total: ₹${o.total} | ${o.time} | Priority: ${priority(o)}</p></div><div class="order-actions">${o.status==="Pending"?`<button class="status-btn" onclick="updateStatus(${o.id},'Preparing')">Preparing</button>`:""}${o.status==="Preparing"?`<button class="status-btn" onclick="updateStatus(${o.id},'Ready')">Ready</button>`:""}${o.status==="Ready"?`<button class="status-btn" onclick="updateStatus(${o.id},'Collected')">Collected</button>`:""}</div></div>`).join(""):"<p>No orders available. Place an order from Student Order.</p>"}
function clearCompleted(){orders=orders.filter(o=>o.status!=="Collected");save();renderOrders()}
function resetOrders(){if(confirm("Reset all demo orders?")){orders=[];save();renderOrders()}}
renderMenu();renderCart();renderOrders();